[package]
name = "pashe-backend"
version = "0.1.0"
edition = "2024"
authors = ["haellsigh@gmail.com"]

[dependencies]
anyhow = "1"
async-trait = "0.1.88"
bytesize = "2.0.1"
chrono = "0.4.41"
clickhouse = { version = "0", features = [
    "chrono",
    "inserter",
    "uuid",
    "uuid",
] }
dotenv = "0"
http = "1.3.1"
oauth2 = "5"
redis = { version = "0", features = ["tokio-comp"] }
reqwest = { version = "0", features = ["json"] }
reqwest-middleware = "0.4.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.15"
tracing = "0"
tracing-subscriber = "0"
tracing-tracy = "0"
url = "2.5.4"
