[package]
name = "pashe-backend"
version = "0.1.0"
edition = "2024"
authors = ["haellsigh@gmail.com"]

[dependencies]
anyhow = "1"
clickhouse = { version = "0", features = [
    "chrono",
    "inserter",
    "uuid",
    "uuid",
] }
dotenv = "0"
oauth2 = "5"
redis = { version = "0", features = ["tokio-comp"] }
reqwest = { version = "0", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0"
tracing-subscriber = "0"
tracing-tracy = "0"
url = "2.5.4"
