services:
  pashe-backend:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  influxdb:
    image: influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_REPORTING_DISABLED="true"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - 8086:8086

volumes:
  redis-data:
  influxdb-data:
