services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  db:
    image: clickhouse/clickhouse-server
    user: 1000:1000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: pashe
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: pashe
      CLICKHOUSE_PASSWORD: pashe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - 8123:8123

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  redis-data:
  clickhouse-data:
  grafana-data:
