name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  db:
    name: Build db binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build db binary
        run: cargo build --bin db

  backend:
    name: Build pashe-backend binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build pashe-backend binary
        run: cargo build --bin pashe-backend

  frontend:
    name: Build and test pashe-frontend
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust for Tauri
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Tauri dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential \
          curl wget file libxdo-dev libssl-dev \
          libayatana-appindicator3-dev librsvg2-dev

      - name: Install frontend dependencies
        run: bun install --cwd crates/pashe-frontend

      - name: Check frontend code
        run: bun --cwd crates/pashe-frontend check

      - name: Run clippy on backend code
        run: cargo clippy -p pashe-frontend

      - name: Build frontend with Tauri
        run: bun --cwd crates/pashe-frontend tauri build --no-bundle
